name: aplikasi_wisata
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
  - images/baturraden1.jpg
  - images/baturraden2.jpg
  - images/baturraden3.jpg
  fonts:
  - family: Oxygen
    fonts:
    - asset: fonts/Oxygen-Regular.ttf
  - family: Staatliches
    fonts:
    - asset: fonts/Staatliches-Regular.ttf
