name: aplikasi_wisata
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
  name: "yourNewAppLauncherName"

flutter:
  uses-material-design: true
  assets: 
  - images/
  fonts:
  - family: Oxygen
    fonts:
    - asset: fonts/Oxygen-Regular.ttf
  - family: Staatliches
    fonts:
    - asset: fonts/Staatliches-Regular.ttf
